name: Checklist

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
      - ready_for_review
      - labeled

jobs:
  detect:
    name: Detect and verify checklists
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - name: Test
        id: test
        run: |
          echo github.head_ref
      - name: Checkbox Trigger
        id: detect
        uses: actions/github-script@v7
        with:
          script: |
            const prDescription = context.payload.pull_request.body || "";

            const checked = [];
            const unchecked = [];
            
            const lines = prDescription.split('\n');
            let isChecklist = false;
            for (const line of lines) {
              if (line.includes("Checklist start")) {
                isChecklist = true;
              }
              if (line.includes("Checklist end")) {
                isChecklist = false;
              }
              
              if (isChecklist && line.startsWith('- [x]')) {
                checked.push(line.substring(6).trim());
              }
              if (isChecklist && line.startsWith('- [ ]') && isChecklist) {
                unchecked.push(line.substring(6).trim());
              }
            }

            if (checked.length > 0) {
              console.log("Checked: ", checked);
            }

            if (unchecked.length > 0) {
              console.log("Unchecked: ", unchecked);
              core.setFailed('Please follow the checklists and update the checklist.');
            }
