name: Checklist

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
      - ready_for_review
      - labeled

jobs:
  detect:
    name: Detect
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    outputs:
      checked: ${{ steps.detect.outputs.checked }}
      unchecked: ${{ steps.detect.outputs.unchecked }}

    steps:
      - name: Checkbox Trigger
        id: detect
        uses: actions/github-script@v7
        with:
          script: |
            const prDescription = context.payload.pull_request.body || ""
            console.log("#pr", prDescription)
            const checked = []
            const unchecked = []
            const lines = prDescription.split('\n')
            let isChecklist = false;
            for (const line of lines) {
              console.log("#line", line);
              if (line.startsWith('- [x]')) {
                checked.push(line.substring(6).trim())
                core.info(`Found checked box: ${line}`)
              }
              if (line.startsWith('- [ ]')) {
                unchecked.push(line.substring(6).trim())
                core.info(`Found unchecked box: ${line}`)
              }
            }
            core.setOutput('checked', checked.join(','))
            core.setOutput('unchecked', unchecked.join(','))
      - name: List changes
        run: |
          echo "checked=${{ steps.detect.outputs.checked }}"
          echo "unchecked=${{ steps.detect.outputs.unchecked }}"

  verify:
    name: Verify
    needs: [detect]
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - name: Self-review
        if: contains(needs.detect.outputs.unchecked, 'I have self-reviewed the code.')
        uses: actions/github-script@v7
        with:
          script: |
            core.setFailed('Please self-review the code and update the Checklist in PR description.')

      - name: Followed standard coding guidelines
        if: contains(needs.detect.outputs.unchecked, 'I have followed the standard coding guidelines.')
        uses: actions/github-script@v7
        with:
          script: |
            core.setFailed('Please follow the standard coding guidelines and update the Checklist in PR description.')

