name: Checklist

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
      - ready_for_review
      - labeled

jobs:
  detect:
    name: Detect and verify checklists
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    outputs:
      checked: ${{ steps.detect.outputs.checked }}
      unchecked: ${{ steps.detect.outputs.unchecked }}

    steps:
      - name: Checkbox Trigger
        id: detect
        uses: actions/github-script@v7
        with:
          script: |
            const script = require('../.github/scripts/getChecklists.js');
            console.log(script({github, context}))
      - name: List changes
        run: |
          echo "checked=${{ steps.detect.outputs.checked }}"
          echo "unchecked=${{ steps.detect.outputs.unchecked }}"
      - name: Verifying checklists
        uses: actions/github-script@v7
        with:
          script: |
            const uncheckedChecklist = steps.detect.outputs.unchecked;
            console.log("#unchec", uncheckedChecklist, uncheckedChecklist.length);
            core.setFailed('Please update the Checklist in PR description.')

