name: Check JIRA

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
      - ready_for_review
      - labeled

jobs:
  detect:
    name: Detect JIRA ticket
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - name: Set up secret file
        env:
          JIRA_PAT: ${{ secrets.JIRA_PAT }}
        run: |
          echo "secrets"
          echo ${{ github.actor }}
          echo "after"
      - name: Detect JIRA
        id: detect
        uses: actions/github-script@v7
        env:
          JIRA_PAT: ${{ secrets.JIRA_PAT }}
        with:
          script: |
            const githubUser = github.rest.users.getByUserName({username: context.actor});
            console.log("#github", context.actor, githubUser);
            const JIRA_TOKEN = `vivekrajwe1@gmail.com:${process.env.JIRA_PAT}`;

            const encodedJIRAToken = `${Buffer.from(JIRA_TOKEN).toString('base64')}`;
            
            fetch('https://vivekrajwe1.atlassian.net/rest/api/2/issue/CRM-3', {
              method: 'GET',
              headers: {
                'Authorization': `Basic ${encodedJIRAToken}`,
                'Accept': 'application/json'
              }
            })
              .then(response => {
                console.log(
                  `Response: ${response.status} ${response.statusText}`
                );
                return response.text();
              })
              .then(text => {
                const jsonText = JSON.parse(text);
                console.log("#json", jsonText);
              })
              .catch(err => console.error("#error", err));
