name: Check JIRA

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
      - ready_for_review
      - labeled

jobs:
  detect:
    name: Detect JIRA ticket
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - name: Detect JIRA
        id: detect
        uses: actions/github-script@v7
        with:
          script: |
            const prDescription = context.payload.pull_request.body || "";

            console.log("#prs", prDescription);
