name: Deploy to main

on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Build version'
        required: true
        default: 'latest'
        type: choice
        options:
        - latest
        - 1.4.1
        - 1.5.1
        - 1.6.1
        - 1.7.1
        - 1.8.1
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Build app
        run: npm run build
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-south-1
      - name: List s3 bucket objects
        env: 
          VERSION: ${{ inputs.version }}
        run: |
          echo "$VERSION"
          aws s3 sync ./dist "s3://zeptosaathi-static-assets/$VERSION"
      - name: Update CloudFront Origin Path
        env:
          CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }}
          NEW_VERSION: ${{ github.event.inputs.version }}
          CLOUDFRONT_ORIGIN_ID: ${{ secrets.AWS_CLOUDFRONT_ORIGIN_ID }}
          VERSION: ${{ inputs.version }}
        run: |
          aws cloudfront get-distribution --id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }} > current-distribution-config.json

          Etag=`cat "current-distribution-config.json" | jq '.ETag' | tr -d \"`

          echo "ETag: $Etag"

          cat "current-distribution-config.json" | jq \
            --arg targetOriginId $CLOUDFRONT_ORIGIN_ID \
            --arg newOriginPath "/$VERSION" \
            '.Distribution.DistributionConfig | .Origins.Items = (.Origins.Items | map(if (.Id == $targetOriginId) then (.OriginPath = $newOriginPath) else . end))' \
            > "latest-distribution-config.json"

          aws cloudfront update-distribution --id $CLOUDFRONT_DISTRIBUTION_ID \
            --distribution-config "file://latest-distribution-config.json" \
            --if-match $Etag \
            > /dev/null
