on: push

name: Jira Example

jobs:
  build:
    runs-on: ubuntu-latest
    name: Jira Example
    steps:
    - name: Login
      uses: atlassian/gajira-login@v3
      env:
        JIRA_BASE_URL: 'https://vivekrajwe1.atlassian.net'
        JIRA_USER_EMAIL: 'vivekrajwe1@gmail.com'
        JIRA_API_TOKEN: ${{ secrets.JIRA_PAT }}

    - name: Jira TODO
      uses: atlassian/gajira-todo@v3
      with:
        project: GA
        issuetype: Task
        description: Created automatically via GitHub Actions
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
