name: PR review notification

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
      - ready_for_review
      - labeled

jobs:
  detect:
    name: Detect and verify checklists
    permissions:
      issues: read
    runs-on: arc-runner-set
    if: github.event.pull_request.draft == false
    steps:
      - name: Notification Trigger
        id: notify
        uses: actions/github-script@v7
        with:
          script: |

            console.log("#github.event.label.name",github.event.label.name);
            const prDescription = context.payload.pull_request.body || "";
            
            const prData = await github.rest.issues.get({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
            })

            console.log("#PR Data: ", prData);

