name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        node-version: [22]
    steps:
        - uses: actions/checkout@v2
          with:
            persist-credentials: false
        - name: Setup Node.js
          uses: actions/setup-node@v1
          with:
            node-version: 18
        - name: Install dependencies
          run: npm install
        - name: Build app
          run: npm run build
        - name: Create Release Pull Request
          uses: changesets/action@v1
          with:
            publish: npm run release
            version: npm run version-packages
          env:
            GITHUB_TOKEN: ${{ secrets.TOKEN }}
